spring:
  data:
    redis:
      host: redis
      port: 6379
  datasource:
    url: ENC(Ky9jQ1kTz+u49I9lPjBVauNEcLKZlG712RWT1lM9g0eL2KmGHiVXYEpiVW7gKIhyZ29XRuK6GRFuZERsBeSEXTrjtj9p3X86QEdjRdsPdX946UGJG45Xp9oDvBtA1uva)
    username: ENC(mAVSIC58xLOew8Eoqox+hA==)
    password: ENC(SJoUAh3qgBbC8t7APRidV6fgQ3+npv3n)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

scheduler:
  cron:
    job: "0 0 6/6 * * *"

custom:
  github:
    client-id: ENC(KP2uJoq4/fKHp20/Ko41G8roZAGa30C75XkuWdpKeKI=)
    client-secret: ENC(n52W++3MJQHP25CWfyQ0gk/id7irOQwXVWCR4Ld7W7Bb8C2tYl0=)
  site:
    baseUrl: https://waveofmymind.shop
