spring:
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    replication:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ENC(mAVSIC58xLOew8Eoqox+hA==)
      password: ENC(SJoUAh3qgBbC8t7APRidV6fgQ3+npv3n)
      write:
        name: write
        url: ENC(IFNoAiPIH/illgvXcB69wRVj+VYYwTqdf6g5huYw5LJUOR6tgpYzP7/rlu1pZ1GKdHFtpmKkrW7AYoHGaTYvAoA02t+ccIVR+EH+q2Bv+A4JjHKQjY12gEUhWuXuprD4)
      reads:
        - name: read1
          url: ENC(OKc5PK/Fj/qGdDtuf1FpRjbD9HaMTapUvnsTHqNpa7GWkElYew6oG91wM6V3yElmNCUarWfTX6PPBLPkuUA2u85mjj87fCc5P5rBKmnly3G2AxBBgobW44WOzRiyi7IPcjsT1Nf5PKk=)
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: wave
    password: 0913
    url: jdbc:mysql://127.0.0.1:3306/goodjob?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect



